kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: template-mono-repo
nodeImage: kindest/node:v1.31.2
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."000000000000.dkr.ecr.us-east-1.localhost:5100"]
      endpoint = ["http://host.docker.internal:5100"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."000000000000.dkr.ecr.us-east-1.localhost:5100".tls]
      insecure_skip_verify = true
