apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: template-mono-repo
type: Opaque
stringData:
  DATABASE_URL: "postgres://template:template@host.docker.internal:5432/template"
  BETTER_AUTH_SECRET: "change-me-to-a-random-string-at-least-32-chars"
